# RoboData Configuration

llm:
  provider: "openai"
  model: "gpt-4o"
  max_tokens: 4096

wikidata:
  timeout: 30
  max_results: 100
  default_language: "en"

neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "robodata123"
  database: "neo4j"
  connection_timeout: 30
  max_connection_lifetime: 3600

toolbox:
  auto_register_wikidata_tools: true
  max_tool_execution_time: 60

interactive:
  show_tool_calls: true
  show_intermediate_steps: true
  max_history_length: 100
