# Example configuration for RoboData using DBpedia instead of Wikidata
# This configuration demonstrates how to use the DBpedia toolbox for knowledge exploration

experiment_id: "dbpedia_example_test"

# Use DBpedia as the knowledge source instead of Wikidata
knowledge_source: "dbpedia"

orchestrator:
  type: "multi_stage"
  context_length: 16000
  model: "gpt-4o"
  memory:
    use_summary_memory: true
    max_memory_slots: 30
  max_turns: 25
  enable_question_decomposition: false
  enable_metacognition: false
  
  metacognition:
    system_description: >
      An AI-powered ontology exploration framework where a metacognitive LLM agent monitors
      and corrects the execution history of a multi-stage LLM-based orchestrator.
      The metacognitive system provides strategic assessment and meta-observation capabilities
      to improve query processing performance through behavioral analysis
      and strategic suggestions for the primary orchestrator agent.
    
    agent_description: >
      Multi-stage orchestrator with six distinct execution phases:
      (1) LOCAL_GRAPH_EXPLORATION using graph database tools (GetNodeTool, CypherQueryTool, GetEdgeTool) to search the accumulated local knowledge graph,
      (2) EVAL_LOCAL_DATA using evaluation tools to assess local search results,
      (3) REMOTE_GRAPH_EXPLORATION using DBpedia API tools (GetEntityInfoTool, SearchEntitiesTool, SPARQLQueryTool, NeighborsExplorationTool, LocalGraphTool) to fetch data from the DBpedia ontology,
      (4) EVAL_REMOTE_DATA using evaluation tools to assess remote retrieval results,
      (5) LOCAL_GRAPH_UPDATE using graph update tools (FetchNodeTool, FetchRelationshipTool, RemoveNodeTool) to populate the local knowledge graph with validated remote data,
      (6) PRODUCE_ANSWER using evaluation tools to generate final responses with supporting evidence from the accumulated graph.
    
    task_description: >
      Systematically explore the DBpedia ontology
      through strategic tool usage to populate a local knowledge graph
      that can answer natural language queries.
      Each answer must be supported by a comprehensive set of nodes
      and relationships from the accumulated local knowledge graph,
      providing complete provenance and evidence chains
      for every statement in the response.

log_level: "DEBUG"
memory: ""

llm:
  provider: "openai"
  model: "gpt-4o"
  temperature: 0.7
  max_tokens: 4096
  # Specific models for different operations
  metacognition_model: "gpt-4o"
  evaluation_model: "gpt-4o"
  exploration_model: "gpt-4o"
  update_model: "gpt-4o"

# Example queries to test DBpedia functionality
queries:
  - "Who is Albert Einstein and what did he discover?"
  - "What are the main works of Douglas Adams?"
  - "Tell me about the relationship between physics and mathematics."

output:
  save_results: true
  export_formats: ["json", "cypher"]
  create_visualizations: true
  results_directory: "experiments"
